# Generated by Django 2.0.6 on 2018-06-24 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='暂无说明', verbose_name='暂无说明'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nickname',
            field=models.CharField(default='超值二手手机', max_length=15, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.PModel', verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.PositiveIntegerField(default=2016, verbose_name='出厂年份'),
        ),
    ]
